/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RetrievingRefreshingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RetrievingRefreshingApiTests
    {
        private RetrievingRefreshingApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RetrievingRefreshingApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RetrievingRefreshingApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RetrievingRefreshingApi
            //Assert.IsInstanceOfType(typeof(RetrievingRefreshingApi), instance, "instance is a RetrievingRefreshingApi");
        }

        
        /// <summary>
        /// Test GetToken
        /// </summary>
        [Test]
        public void GetTokenTest()
        {
            // TODO uncomment below to test the method and replace placeholders with values
            // obtained from the Authorize.Net Sandbox portal:
            // https://sandbox.authorize.net  →  Account  →  Settings  →  Security Settings  →  API Credentials & Keys
            string grantType = "authorization_code";
            string clientId = "[YOUR_CLIENT_ID]";
            string code = "[YOUR_AUTHORIZATION_CODE]";
            string clientSecret = "[YOUR_CLIENT_SECRET]";
            string refreshToken = null;
            int? platform = 2;
            var response = instance.GetToken(grantType, clientId, code, clientSecret, refreshToken, platform);
            Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
    }

}
